# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

# Web framework
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'puma', '~> 6.0'

# JSON handling
gem 'json', '~> 2.7'

# CORS support
gem 'rack-cors', '~> 2.0'

# Environment variables
gem 'dotenv', '~> 3.0'

group :development do
  gem 'rerun', '~> 0.14'
  gem 'rubocop', '~> 1.60'
end

group :test do
  gem 'rack-test', '~> 2.1'
  gem 'rspec', '~> 3.13'
  gem 'webmock', '~> 3.20'
end

group :development, :test do
  gem 'pry', '~> 0.14'
end
