org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

# Force Gradle to use Java 17 (required for React Native 0.73.x)
org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home

android.useAndroidX=true
android.enableJetifier=true

newArchEnabled=false

hermesEnabled=true
